spring:
  application:
    name: netflix-eureka-naming-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-regitry: false
  server:
    renewalPercentThreshold: 0.33